// swift-tools-version: 5.9

import PackageDescription

let package = Package(
  name: "VescBle",
  platforms: [.iOS(.v16)],
  products: [
    .library(name: "VescBle", targets: ["VescBle"]),
  ],
  dependencies: [],
  targets: [
    .target(
      name: "VescBle",
      dependencies: [],
      path: "ios",
      exclude: [
        "alerts/alert_beep.wav",
        "alerts/alert_gamma.wav",
        "alerts/alert_notify.wav",
        "alerts/alert_sustained.wav",
        "alerts/alert_tick_hard.wav",
        "alerts/alert_tick.wav",
        "alerts/alert_urgent.wav",
        "alerts/off.wav",
        "alerts/on.wav",
        "alerts/AlertAudioPlayer.swift",
        "alerts/AlertCoordinator.swift",
        "alerts/AlertEngineTests.swift",
        "BatterySocEstimatorTests.swift",
        "ConfigReadController.swift",
        "connection/BoardTransportDetector.swift",
        "connection/ConnectionCoordinator.swift",
        "DiagnosticReporter.swift",
        "diagnostics/DiagnosticsRecorder.swift",
        "LiveSeriesDownsamplerTests.swift",
        "RefloatConfigDecoderTests.swift",
        "RefloatConfigProtocolTests.swift",
        "RefloatConfigSchemaTests.swift",
        "notification/RideActivityAttributes.swift",
        "notification/RideActivityContent.swift",
        "recording/RecordingCoordinator.swift",
        "RideActivityContentTests.swift",
        "runtime/BoardSession.swift",
        "SocMedianWindowTests.swift",
        "telemetry/AppDataRepository+PrivacyZones.swift",
        "telemetry/DatabaseBackupManager.swift",
        "telemetry/MetricSanitizer.swift",
        "telemetry/PrivacyZoneFilterTests.swift",
        "telemetry/IdlePauseDetectorTests.swift",
        "telemetry/TelemetryRepository.swift",
        "telemetry/TuneProfileStore.swift",
        "telemetry/TuneProfileStoreTests.swift",
        "telemetry/ZipArchive.swift",
        "TransportDetectionTests.swift",
        "VescBleModule.swift",
        "VescBle.podspec",
        "VescGattClient.swift",
        "VescGpsMonitor.swift",
        "VescProtocolTests.swift",
        "notification/RideLiveActivityController.swift",
      ],
      sources: [
        "alerts/AlertEngine.swift",
        "connection/TransportDetection.swift",
        "telemetry/BatterySocEstimator.swift",
        "telemetry/IdlePauseDetector.swift",
        "telemetry/LiveSeriesDownsampler.swift",
        "telemetry/LiveSeriesEmitter.swift",
        "telemetry/PrivacyZoneFilter.swift",
        "telemetry/SocMedianWindow.swift",
        "RefloatConfigDecoder.swift",
        "RefloatConfigModels.swift",
        "RefloatConfigProtocol.swift",
        "RefloatConfigSchema.swift",
        "RefloatXmlNode.swift",
        "VescGpsPrecision.swift",
        "VescProtocol.swift",
      ],
      resources: [
        .process("cell-presets.json"),
      ]
    ),
    .testTarget(
      name: "VescBleTests",
      dependencies: ["VescBle"],
      path: "ios",
      sources: [
        "alerts/AlertEngineTests.swift",
        "telemetry/PrivacyZoneFilterTests.swift",
        "telemetry/IdlePauseDetectorTests.swift",
        "BatterySocEstimatorTests.swift",
        "LiveSeriesDownsamplerTests.swift",
        "LiveSeriesEmitterTests.swift",
        "RefloatConfigDecoderTests.swift",
        "RefloatConfigProtocolTests.swift",
        "RefloatConfigSchemaTests.swift",
        "SocMedianWindowTests.swift",
        "TransportDetectionTests.swift",
        "VescProtocolTests.swift",
      ]
    ),
  ]
)
