// swift-tools-version: 5.9

import PackageDescription

let package = Package(
  name: "VescapeCore",
  platforms: [.iOS(.v16), .macOS(.v10_15)],
  products: [
    .library(name: "VescapeCore", targets: ["VescapeCore"]),
  ],
  dependencies: [],
  targets: [
    .target(
      name: "VescapeCore",
      dependencies: [],
      path: "ios",
      exclude: [
        "alerts/alert_beep.wav",
        "alerts/alert_gamma.wav",
        "alerts/alert_notify.wav",
        "alerts/alert_sustained.wav",
        "alerts/alert_tick_hard.wav",
        "alerts/alert_tick.wav",
        "alerts/alert_urgent.wav",
        "alerts/off.wav",
        "alerts/on.wav",
        "alerts/AlertAudioPlayer.swift",
        "alerts/AlertCoordinator.swift",
        "alerts/AlertEngineTests.swift",
        "telemetry/BatterySocEstimatorTests.swift",
        "connection/BoardTransportDetector.swift",
        "connection/BoardSessionController.swift",
        "diagnostics/DiagnosticReporter.swift",
        "diagnostics/DiagnosticsRecorder.swift",
        "telemetry/LiveSeriesDownsamplerTests.swift",
        "config/RefloatConfigDecoderTests.swift",
        "config/RefloatConfigProtocolTests.swift",
        "config/RefloatConfigSchemaTests.swift",
        "notification/RideActivityAttributes.swift",
        "notification/RideActivityContent.swift",
        "recording/RecordingCoordinator.swift",
        "config/RefloatConfigEncoderTests.swift",
        "config/RefloatConfigWriteVerifierTests.swift",
        "notification/RideActivityContentTests.swift",
        "runtime/BoardSessionLinkIntegrityTests.swift",
        "telemetry/SocMedianWindowTests.swift",
        "telemetry/AppDataRepository+PrivacyZones.swift",
        "telemetry/AppDataRepository.swift",
        "telemetry/DatabaseBackupManager.swift",
        "telemetry/LiveSeriesEmitterTests.swift",
        "telemetry/MetricSanitizer.swift",
        "telemetry/PrivacyZoneFilterTests.swift",
        "telemetry/ProfileStatsRepository.swift",
        "telemetry/IdlePauseDetectorTests.swift",
        "telemetry/TelemetryBucketBuilder.swift",
        "telemetry/TelemetryDao.swift",
        "telemetry/TelemetryDatabase.swift",
        "telemetry/TelemetryPipeline.swift",
        "telemetry/TelemetryRepository.swift",
        "telemetry/TuneProfileStore.swift",
        "telemetry/TuneProfileStoreTests.swift",
        "telemetry/ZipArchive.swift",
        "connection/TransportDetectionTests.swift",
        "VescapeCoreModule.swift",
        "VescapeCore.podspec",
        "protocol/VescGattClient.swift",
        "replay/ReplayTransport.swift",
        "replay/ReplayRecordings.swift",
        "fixtures",
        "location/GpsMonitor.swift",
        "protocol/VescProtocolTests.swift",
        "notification/RideLiveActivityController.swift",
        "appstatus/AppStatusTests.swift",
        "appstatus/AppStatusCoordinatorTests.swift",
      ],
      sources: [
        "alerts/AlertEngine.swift",
        "appstatus/AppStatus.swift",
        "appstatus/AppStatusCoordinator.swift",
        "config/ConfigRWController.swift",
        "warnings/ConfigSafetyDetector.swift",
        "connection/BoardPhase.swift",
        "connection/TransportDetection.swift",
        "warnings/BatteryConfigMismatchDetector.swift",
        "telemetry/BatterySocEstimator.swift",
        "telemetry/BoardLinkPersistence.swift",
        "warnings/BoardWarningKind.swift",
        "warnings/CellSpreadDetector.swift",
        "telemetry/IdlePauseDetector.swift",
        "telemetry/LiveSeriesDownsampler.swift",
        "telemetry/LiveSeriesEmitter.swift",
        "telemetry/PrivacyZoneFilter.swift",
        "telemetry/SocMedianWindow.swift",
        "config/RefloatConfigDecoder.swift",
        "config/RefloatConfigEncoder.swift",
        "config/RefloatConfigModels.swift",
        "config/RefloatConfigProtocol.swift",
        "config/RefloatConfigSchema.swift",
        "config/RefloatConfigWriteVerifier.swift",
        "runtime/BoardSession.swift",
        "config/RefloatXmlNode.swift",
        "location/GpsPrecision.swift",
        "location/LegalPolicyResolver.swift",
        "protocol/VescProtocol.swift",
        "replay/ReplayChunkDecoder.swift",
        "recording/SessionRecorder.swift",
      ],
      resources: [
        .process("cell-presets.json"),
      ]
    ),
    .testTarget(
      name: "VescapeCoreTests",
      dependencies: ["VescapeCore"],
      path: "ios",
      sources: [
        "alerts/AlertEngineTests.swift",
        "appstatus/AppStatusTests.swift",
        "appstatus/AppStatusCoordinatorTests.swift",
        "warnings/BatteryConfigMismatchDetectorTests.swift",
        "warnings/BoardWarningPayloadTests.swift",
        "warnings/CellSpreadDetectorTests.swift",
        "warnings/ConfigSafetyDetectorTests.swift",
        "telemetry/PrivacyZoneFilterTests.swift",
        "telemetry/IdlePauseDetectorTests.swift",
        "telemetry/BatterySocEstimatorTests.swift",
        "telemetry/AppDataRepositoryBoardLinkTests.swift",
        "telemetry/LiveSeriesDownsamplerTests.swift",
        "telemetry/LiveSeriesEmitterTests.swift",
        "config/RefloatConfigDecoderTests.swift",
        "config/RefloatConfigEncoderTests.swift",
        "config/RefloatConfigProtocolTests.swift",
        "config/RefloatConfigSchemaTests.swift",
        "config/RefloatConfigWriteVerifierTests.swift",
        "telemetry/SocMedianWindowTests.swift",
        "runtime/BoardSessionLinkIntegrityTests.swift",
        "location/LegalPolicyResolverTests.swift",
        "config/ConfigRWControllerLinkIntegrityTests.swift",
        "connection/TransportDetectionTests.swift",
        "protocol/VescProtocolTests.swift",
        "replay/WarningReplayHarnessTests.swift",
        "replay/WarningReplayScenarioTests.swift",
        "replay/NoBmsRideReplayTests.swift",
        "replay/ConfigReplayHarness.swift",
        "replay/ConfigReplayHarnessTests.swift",
        "recording/SessionRecorderTests.swift",
      ]
    ),
  ]
)
