import {
  AndroidConfig,
  withAndroidManifest,
  withAppBuildGradle,
  type ConfigPlugin,
} from 'expo/config-plugins'

/**
 * Starts the Sentry Android SDK (including the NDK signal handlers) from the
 * manifest-driven ContentProvider — before `Application.onCreate`, native module
 * static init, and long before the JS bundle loads.
 *
 * `@sentry/react-native` ships `io.sentry.auto-init=false` in its library
 * manifest because it expects `Sentry.init()` in JS to boot the native SDK.
 * That leaves a blind spot: a native crash during startup (BLE module, Mapbox,
 * any Kotlin init) kills the app before JS runs, so nothing is ever captured —
 * and in a crash loop, previously cached envelopes are never uploaded either.
 * Overriding auto-init to true (with `tools:replace`, since the library value
 * would otherwise win the manifest merge) closes that gap. The later JS
 * `Sentry.init()` simply re-initializes the native SDK with the JS options.
 *
 * The `io.sentry.environment` meta-data uses a gradle manifest placeholder so
 * the single prebuild-generated manifest still yields the right environment per
 * build type (debug → development, release → production), matching the JS-side
 * `environment` in `src/config/sentry.ts`.
 *
 * No-op when `EXPO_PUBLIC_SENTRY_DSN` is unset at prebuild time.
 */
const GRADLE_PLACEHOLDERS = `
// @generated by plugins/withSentryNativeInit — per-build-type Sentry environment
android.buildTypes.debug.manifestPlaceholders += [sentryEnvironment: "development"]
android.buildTypes.release.manifestPlaceholders += [sentryEnvironment: "production"]
`

const withSentryNativeInit: ConfigPlugin = (config) => {
  const dsn = process.env.EXPO_PUBLIC_SENTRY_DSN
  if (!dsn) return config

  config = withAndroidManifest(config, (cfg) => {
    cfg.modResults.manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools'
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(app, 'io.sentry.dsn', dsn)
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(app, 'io.sentry.auto-init', 'true')
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      'io.sentry.environment',
      '${sentryEnvironment}',
    )

    const autoInit = app['meta-data']?.find(
      (item) => item.$['android:name'] === 'io.sentry.auto-init',
    )
    if (autoInit) {
      ;(autoInit.$ as Record<string, string>)['tools:replace'] = 'android:value'
    }
    return cfg
  })

  return withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes('sentryEnvironment')) {
      cfg.modResults.contents += GRADLE_PLACEHOLDERS
    }
    return cfg
  })
}

export default withSentryNativeInit
