import { withAppBuildGradle, type ConfigPlugin } from 'expo/config-plugins'

/**
 * Injects an upload-key signingConfig into the generated android/app/build.gradle.
 *
 * Because android/ is gitignored and regenerated by expo prebuild on every CI
 * run, signing configuration cannot live in build.gradle directly — it must be
 * a plugin so it is re-applied on each prebuild.
 *
 * At build time the config reads four Gradle project properties, passed via
 * fastlane's `gradle(properties: {...})` or -P flags:
 *
 *   VESCAPE_UPLOAD_STORE_FILE      – absolute path to the keystore file
 *   VESCAPE_UPLOAD_STORE_PASSWORD  – store password
 *   VESCAPE_UPLOAD_KEY_ALIAS       – key alias
 *   VESCAPE_UPLOAD_KEY_PASSWORD    – key password
 *
 * The `hasProperty` guard means local dev builds and scripts/release.ts (which
 * use the debug keystore) continue working unchanged when the props are absent.
 */
const withAndroidSigningConfig: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (cfg) => {
    let { contents } = cfg.modResults

    // Idempotency — skip if already injected
    if (contents.includes('VESCAPE_UPLOAD_STORE_FILE')) {
      return cfg
    }

    // 1. Insert a release signingConfig right after the debug block's closing brace
    //    inside signingConfigs { }. The Expo template always ends the debug block
    //    with `keyPassword 'android'` followed by a closing brace on its own line.
    contents = contents.replace(
      /(signingConfigs\s*\{[\s\S]*?keyPassword\s+'android'\n\s*\})/,
      `$1
        release {
            if (project.hasProperty('VESCAPE_UPLOAD_STORE_FILE')) {
                storeFile file(VESCAPE_UPLOAD_STORE_FILE)
                storePassword VESCAPE_UPLOAD_STORE_PASSWORD
                keyAlias VESCAPE_UPLOAD_KEY_ALIAS
                keyPassword VESCAPE_UPLOAD_KEY_PASSWORD
            }
        }`,
    )

    // 2. Repoint the release buildType from the debug signingConfig to the release one.
    //    Lazy matching ensures only the signingConfig inside `release { }` is replaced,
    //    not the one inside `debug { }` which appears first in the file.
    contents = contents.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig\s+signingConfigs\.debug/,
      "$1signingConfig project.hasProperty('VESCAPE_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug",
    )

    cfg.modResults.contents = contents
    return cfg
  })

export default withAndroidSigningConfig
