import type { Href } from 'expo-router'

export const routes = {
  home: '/',
  profile: '/profile',
  settings: '/settings',
  settingsDev: '/settings/dev',
  settingsComponents: '/settings/components',
  settingsDiagnostic: '/settings/diagnostic',
  settingsOther: '/settings/other',
  tune: '/tune',
  tuneHistory: '/tune/history',
  addBoardScan: '/addBoard/scan',
  addBoardDetails: '/addBoard/details',
  controlSpeed: '/control/speed',
  controlBattery: '/control/battery',
  controlDuty: '/control/duty',
  controlTemperatures: '/control/temperatures',
  controlCurrents: '/control/currents',
  controlState: '/control/state',
  controlFootpad: '/control/footpad',
  controlImu: '/control/imu',
  settingsSoundPlayground: '/settings/soundPlayground' as Href,
  settingsDiagnosticEvents: '/settings/eventLog' as Href,
} as const

export const stackScreens = {
  home: 'index',
  profile: 'profile',
  settings: 'settings',
  settingsDev: 'settings/dev',
  settingsComponents: 'settings/components',
  settingsDiagnostic: 'settings/diagnostic',
  settingsDiagnosticEvents: 'settings/eventLog',
  settingsOther: 'settings/other',
  tune: 'tune/index',
  tuneHistory: 'tune/history',
  addBoardScan: 'addBoard/scan',
  addBoardDetails: 'addBoard/details',
  settingsSoundPlayground: 'settings/soundPlayground',
} as const
