import type { Href } from 'expo-router'

export const routes = {
  home: '/',
  profile: '/profile',
  settings: '/settings',
  settingsDev: '/settings/dev',
  settingsDebugRecordings: '/settings/debug-recordings' as Href,
  settingsComponents: '/settings/components',
  settingsDiagnostic: '/settings/diagnostic',
  settingsNavigationDiagnostic: '/settings/navigationDiagnostic',
  settingsOther: '/settings/other',
  tune: '/tune',
  tuneHistory: '/tune/history',
  addBoardScan: '/addBoard/scan',
  addBoard: '/addBoard',
  editBoard: '/editBoard/[boardId]',
  editBoardLink: '/editBoard/link',
  controlSpeed: '/control/speed',
  controlBattery: '/control/battery',
  controlDuty: '/control/duty',
  controlTemperatures: '/control/temperatures',
  controlCurrents: '/control/currents',
  controlState: '/control/state',
  controlFootpad: '/control/footpad',
  controlImu: '/control/imu',
  settingsSoundPlayground: '/settings/soundPlayground' as Href,
  settingsDiagnosticEvents: '/settings/eventLog' as Href,
  settingsPrivacyZones: '/settings/privacy-zones' as Href,
  settingsLiveTelemetry: '/settings/live-telemetry' as Href,
  settingsFilters: '/settings/filters' as Href,
  settingsGraphs: '/settings/graphs' as Href,
  settingsDatabase: '/settings/database' as Href,
  settingsAbout: '/settings/about' as Href,
} as const

export const stackScreens = {
  home: 'index',
  profile: 'profile',
  settings: 'settings',
  settingsDev: 'settings/dev',
  settingsDebugRecordings: 'settings/debug-recordings',
  settingsComponents: 'settings/components',
  settingsDiagnostic: 'settings/diagnostic',
  settingsNavigationDiagnostic: 'settings/navigationDiagnostic',
  settingsDiagnosticEvents: 'settings/eventLog',
  settingsOther: 'settings/other',
  tune: 'tune/index',
  tuneHistory: 'tune/history',
  addBoardScan: 'addBoard/scan',
  addBoard: 'addBoard/index',
  editBoard: 'editBoard/[boardId]',
  editBoardLink: 'editBoard/link',
  settingsSoundPlayground: 'settings/soundPlayground',
  settingsPrivacyZones: 'settings/privacy-zones',
  settingsLiveTelemetry: 'settings/live-telemetry',
  settingsFilters: 'settings/filters',
  settingsGraphs: 'settings/graphs',
  settingsDatabase: 'settings/database',
  settingsAbout: 'settings/about',
} as const
