import type { Href } from 'expo-router'

export const routes = {
  home: '/',
  profile: '/profile',
  settings: '/settings',
  settingsDev: '/settings/dev',
  settingsComponents: '/settings/components',
  settingsDiagnostic: '/settings/diagnostic',
  settingsNavigationDiagnostic: '/settings/navigationDiagnostic',
  settingsOther: '/settings/other',
  tune: '/tune',
  tuneHistory: '/tune/history',
  addBoardScan: '/addBoard/scan',
  addBoard: '/addBoard',
  editBoard: '/editBoard/[boardId]',
  controlSpeed: '/control/speed',
  controlBattery: '/control/battery',
  controlDuty: '/control/duty',
  controlTemperatures: '/control/temperatures',
  controlCurrents: '/control/currents',
  controlState: '/control/state',
  controlFootpad: '/control/footpad',
  controlImu: '/control/imu',
  settingsSoundPlayground: '/settings/soundPlayground' as Href,
  settingsDiagnosticEvents: '/settings/eventLog' as Href,
  settingsPrivacyZones: '/settings/privacy-zones' as Href,
  settingsTelemetryTiming: '/settings/telemetryTiming' as Href,
} as const

export const stackScreens = {
  home: 'index',
  profile: 'profile',
  settings: 'settings',
  settingsDev: 'settings/dev',
  settingsComponents: 'settings/components',
  settingsDiagnostic: 'settings/diagnostic',
  settingsNavigationDiagnostic: 'settings/navigationDiagnostic',
  settingsDiagnosticEvents: 'settings/eventLog',
  settingsOther: 'settings/other',
  tune: 'tune/index',
  tuneHistory: 'tune/history',
  addBoardScan: 'addBoard/scan',
  addBoard: 'addBoard/index',
  editBoard: 'editBoard/[boardId]',
  settingsSoundPlayground: 'settings/soundPlayground',
  settingsPrivacyZones: 'settings/privacy-zones',
  settingsTelemetryTiming: 'settings/telemetryTiming',
} as const
